name: StellaCore
version: '1.0.2'
main: me.namioll.stellaCore.StellaCore
api-version: '1.21'
authors: [ _Lolliman_ ]
description: ":)"
depend: [ ItemsAdder ]
commands:
  getmagics:
  stream:
  link:
  banwords:
  sud:
  menu:
  mc:
  pygalka:
  alarm:
  chatreload: